### ISSUE TITLE
Request for config/bin output

### ISSUE THREAD

**Issue by inverted360** [georgechang/sitecore-xdb-documentdb-processor#1]
Hi George,

Is it possible to apply your solution without compiling a Sitecore install package? Can this capability be enabled by placing a .dll file in the \bin folder and referencing it with a .config file in \App_Config?

**Comment by georgechang** [comment]
Yes it can. I'll update the release with just the files.

**Comment by georgechang** [comment]
DLL and config patch file has been added to the release. Drop the .config file in your App_Config/Include folder and the DLL in the bin folder and you should be good to go.

**Comment by inverted360** [comment]
Thanks! Do you know if Sitecore 8.1.2 supports the 'sslValidate' flag? I was able to get DocDB working if I dropped the flag, but curious. 


Nested Exception

Exception: System.ArgumentException
Message: Invalid option 'sslValidate'.
Parameter name: url
Source: MongoDB.Driver
   at MongoDB.Driver.MongoUrlBuilder.Parse(String url)
   at MongoDB.Driver.MongoUrl..ctor(String url)
   at Sitecore.Analytics.Data.DataAccess.MongoDb.MongoDbDriver..ctor(String connectionString, Boolean failOnReadErrors, MongoDbProfiler profiler)
   at Sitecore.Analytics.Data.DataAccess.MongoDb.MongoDbDriver..ctor(String connectionString, String failOnReadErrors)

**Comment by georgechang** [comment]
My guess is that the version of the C# MongoDB driver doesn't support the flag. Sitecore 8 is using an older 1.10 version of the driver rather than the new 2.x versions.
